image: python:3.10.6

pipelines:
  default:
    - parallel:
      - step:
          name: 'Install Dependencies'
          script:
            - pip3 install requests
      - step:
          name: 'Extend'
          script:
            - python3 run.py -u $USERNAME -p $PASSWORD